import Image from 'next/image';
import Link from 'next/link';
import mark from '@/public/brand/buzzin-mark.png';
import { cx } from '@/lib/util/cx';

/** Intrinsic size of `buzzin-mark.png`, generated by scripts/generate-brand-assets.mjs. */
const MARK_WIDTH = 214;
const MARK_HEIGHT = 288;

/**
 * The mark: the leaf with a bolt cut through it.
 *
 * A raster rather than inline SVG, because the artwork is gradient-shaded and
 * tracing it would lose exactly what makes it the logo. `next/image` re-encodes
 * it to AVIF or WebP at the size actually asked for, so the header pays a few
 * hundred bytes for it.
 *
 * `size` is the mark's *height*. The leaf is taller than it is wide, so height
 * is what controls how large it reads, and the width follows the source's
 * aspect ratio — unlike the square mark this replaced, which took one number
 * for both.
 */
export function Logo({ size = 30, className }: { size?: number; className?: string }) {
  return (
    <Image
      src={mark}
      alt=""
      width={Math.round((MARK_WIDTH / MARK_HEIGHT) * size)}
      height={size}
      // The header is above the fold on every page, and the mark is ~1 KB at
      // this size. Lazy-loading it only buys a blank slot on first paint.
      loading="eager"
      className={className}
    />
  );
}

export function Wordmark({
  href = '/',
  size = 'md',
  className,
}: {
  href?: string | null;
  size?: 'sm' | 'md';
  className?: string;
}) {
  const content = (
    <span className={cx('inline-flex items-center gap-2.5', className)}>
      <Logo size={size === 'sm' ? 24 : 30} />
      <span
        className={cx(
          'font-semibold tracking-tight text-ink-50',
          size === 'sm' ? 'text-sm' : 'text-[17px]',
        )}
      >
        BuzzIn
      </span>
    </span>
  );
  if (!href) return content;
  return (
    <Link href={href} className="rounded-lg transition-opacity hover:opacity-80">
      {content}
    </Link>
  );
}
