import type { Challenge } from '@/lib/types';

type Seed = Omit<Challenge, 'id' | 'gameType' | 'source' | 'status'>;

/**
 * Approved local question pool. Used whenever the AI provider is unavailable,
 * when the host asks for "Use Seeded Questions", and to top up a short AI set.
 * Every entry is already in the approved-question shape: four distinct options,
 * exactly one correct index, and a non-empty explanation.
 */
const SEEDS: Seed[] = [
  {
    question: 'What does a blockchain "block" primarily contain?',
    options: ['A batch of transactions', 'A single user account', 'A private key', 'A DNS record'],
    correctAnswerIndex: 0,
    difficulty: 1,
    topic: 'Web3 Basics',
    explanation: 'A block bundles a batch of ordered transactions plus a header linking it to the previous block.',
  },
  {
    question: 'What is a wallet seed phrase used for?',
    options: [
      'Recovering the keys that control an account',
      'Paying network gas fees',
      'Naming your wallet',
      'Encrypting a website',
    ],
    correctAnswerIndex: 0,
    difficulty: 1,
    topic: 'Wallets',
    explanation: 'A seed phrase deterministically regenerates the private keys for every account in a wallet.',
  },
  {
    question: 'Which unit measures computational work on Ethereum?',
    options: ['Gas', 'Watt', 'Hash', 'Nonce'],
    correctAnswerIndex: 0,
    difficulty: 1,
    topic: 'Ethereum',
    explanation: 'Gas meters the computational effort of each operation; users pay for the gas they consume.',
  },
  {
    question: 'What does EVM stand for?',
    options: [
      'Ethereum Virtual Machine',
      'Encrypted Value Manager',
      'Extended Validation Method',
      'Ethereum Verification Module',
    ],
    correctAnswerIndex: 0,
    difficulty: 1,
    topic: 'Ethereum',
    explanation: 'The Ethereum Virtual Machine is the runtime that executes smart contract bytecode.',
  },
  {
    question: 'What is the native token of the Monad network?',
    options: ['MON', 'MND', 'MONA', 'ETH'],
    correctAnswerIndex: 0,
    difficulty: 1,
    topic: 'Monad',
    explanation: 'MON is the native gas and staking asset of the Monad network.',
  },
  {
    question: 'Monad is best described as which kind of chain?',
    options: [
      'An EVM-compatible Layer 1',
      'A Bitcoin sidechain',
      'A centralised database',
      'A non-programmable payment rail',
    ],
    correctAnswerIndex: 0,
    difficulty: 2,
    topic: 'Monad',
    explanation: 'Monad is a high-performance Layer 1 that keeps full EVM bytecode compatibility.',
  },
  {
    question: 'Which Monad feature lets transactions run concurrently while preserving ordering?',
    options: [
      'Optimistic parallel execution',
      'Proof of work mining',
      'Off-chain batching only',
      'Manual sharding by users',
    ],
    correctAnswerIndex: 0,
    difficulty: 3,
    topic: 'Monad',
    explanation: 'Monad executes transactions optimistically in parallel and re-executes any that conflict, producing the same result as serial execution.',
  },
  {
    question: 'What is the default visibility of a Solidity state variable declared without a modifier?',
    options: ['internal', 'public', 'private', 'external'],
    correctAnswerIndex: 0,
    difficulty: 3,
    topic: 'Solidity',
    explanation: 'State variables default to `internal`, reachable by the contract and its descendants only.',
  },
  {
    question: 'Which Solidity keyword makes a function reject incoming Ether?',
    options: [
      'Omitting `payable`',
      'Adding `view`',
      'Adding `virtual`',
      'Adding `memory`',
    ],
    correctAnswerIndex: 0,
    difficulty: 2,
    topic: 'Solidity',
    explanation: 'Only functions marked `payable` can receive Ether; every other function reverts on a non-zero value.',
  },
  {
    question: 'What does the `view` modifier promise in Solidity?',
    options: [
      'The function does not modify state',
      'The function is free to call on-chain',
      'The function is private',
      'The function can receive Ether',
    ],
    correctAnswerIndex: 0,
    difficulty: 2,
    topic: 'Solidity',
    explanation: '`view` declares that the function reads but never writes contract state.',
  },
  {
    question: 'Which pattern best prevents a reentrancy attack?',
    options: [
      'Checks-Effects-Interactions',
      'Interactions-Checks-Effects',
      'Storing balances in memory',
      'Using tx.origin for auth',
    ],
    correctAnswerIndex: 0,
    difficulty: 3,
    topic: 'Smart Contract Security',
    explanation: 'Updating state before making external calls removes the window a reentrant call could exploit.',
  },
  {
    question: 'Why is `tx.origin` unsafe for authorisation?',
    options: [
      'A malicious intermediate contract can forward a victim call',
      'It is always the zero address',
      'It costs too much gas',
      'It is deprecated in every EVM chain',
    ],
    correctAnswerIndex: 0,
    difficulty: 4,
    topic: 'Smart Contract Security',
    explanation: '`tx.origin` is the original signer, so a contract the victim calls can act on their behalf. Use `msg.sender`.',
  },
  {
    question: 'A pull-payment withdrawal pattern mainly protects against what?',
    options: [
      'A failing recipient blocking the whole payout loop',
      'High gas prices',
      'Front-running of swaps',
      'Signature malleability',
    ],
    correctAnswerIndex: 0,
    difficulty: 4,
    topic: 'Smart Contract Security',
    explanation: 'With pull payments each recipient withdraws independently, so one reverting transfer cannot brick the distribution.',
  },
  {
    question: 'What is an ERC-20 token?',
    options: [
      'A fungible token standard',
      'A non-fungible token standard',
      'A consensus algorithm',
      'A wallet format',
    ],
    correctAnswerIndex: 0,
    difficulty: 1,
    topic: 'DeFi',
    explanation: 'ERC-20 defines the standard interface for interchangeable, fungible tokens.',
  },
  {
    question: 'Which standard is used for non-fungible tokens?',
    options: ['ERC-721', 'ERC-20', 'ERC-1559', 'ERC-4337'],
    correctAnswerIndex: 0,
    difficulty: 2,
    topic: 'NFTs',
    explanation: 'ERC-721 gives every token a unique id, which is what makes it non-fungible.',
  },
  {
    question: 'What does an automated market maker replace?',
    options: [
      'A traditional order book',
      'A block explorer',
      'A hardware wallet',
      'A consensus client',
    ],
    correctAnswerIndex: 0,
    difficulty: 2,
    topic: 'DeFi',
    explanation: 'An AMM prices trades from a liquidity pool formula instead of matching buy and sell orders.',
  },
  {
    question: 'What is impermanent loss?',
    options: [
      'Value lost by a liquidity provider when pool prices diverge',
      'Gas wasted on a reverted transaction',
      'A failed bridge transfer',
      'Slashing of a validator stake',
    ],
    correctAnswerIndex: 0,
    difficulty: 4,
    topic: 'DeFi',
    explanation: 'When the pool ratio moves, an LP ends up with less value than simply holding the two assets.',
  },
  {
    question: 'What does ERC-4337 introduce?',
    options: [
      'Account abstraction without protocol changes',
      'A new NFT metadata format',
      'A faster hashing algorithm',
      'A layer-2 rollup standard',
    ],
    correctAnswerIndex: 0,
    difficulty: 4,
    topic: 'Wallets',
    explanation: 'ERC-4337 enables smart-contract accounts through a separate user-operation mempool, with no consensus change.',
  },
  {
    question: 'What is a Layer 2?',
    options: [
      'A network that settles its state onto a Layer 1',
      'A second copy of the same blockchain',
      'A wallet backup',
      'A type of hardware node',
    ],
    correctAnswerIndex: 0,
    difficulty: 2,
    topic: 'Layer 2s',
    explanation: 'A Layer 2 executes transactions off the base chain and posts data or proofs back to Layer 1 for settlement.',
  },
  {
    question: 'How does an optimistic rollup differ from a ZK rollup?',
    options: [
      'It assumes validity and relies on a fraud-proof window',
      'It never posts data to Layer 1',
      'It cannot run EVM bytecode',
      'It requires proof of work',
    ],
    correctAnswerIndex: 0,
    difficulty: 4,
    topic: 'Layer 2s',
    explanation: 'Optimistic rollups accept batches by default and allow challenges during a dispute window; ZK rollups prove validity up front.',
  },
  {
    question: 'What did EIP-1559 change about Ethereum fees?',
    options: [
      'It added a burned base fee plus a priority tip',
      'It removed all fees',
      'It made fees fixed forever',
      'It moved fees off-chain',
    ],
    correctAnswerIndex: 0,
    difficulty: 3,
    topic: 'Ethereum',
    explanation: 'EIP-1559 split the fee into an algorithmic base fee that is burned and a tip paid to the block proposer.',
  },
  {
    question: 'What is the purpose of a nonce on an EVM account?',
    options: [
      'It orders transactions and prevents replays',
      'It stores the account balance',
      'It encrypts the private key',
      'It identifies the chain',
    ],
    correctAnswerIndex: 0,
    difficulty: 3,
    topic: 'Ethereum',
    explanation: 'Each account nonce increments per transaction, fixing the order and making replays invalid.',
  },
  {
    question: 'What is finality on a blockchain?',
    options: [
      'The point at which a transaction can no longer be reverted',
      'The last block ever produced',
      'The moment a wallet is created',
      'The expiry of a smart contract',
    ],
    correctAnswerIndex: 0,
    difficulty: 3,
    topic: 'Layer 1s',
    explanation: 'Finality is the guarantee that a confirmed transaction will not be reorganised out of the chain.',
  },
  {
    question: 'In proof of stake, what does slashing do?',
    options: [
      'Destroys part of a misbehaving validator stake',
      'Reduces gas fees for users',
      'Doubles staking rewards',
      'Splits a block in half',
    ],
    correctAnswerIndex: 0,
    difficulty: 3,
    topic: 'Layer 1s',
    explanation: 'Slashing burns a portion of a validator stake as the economic penalty for provable misbehaviour.',
  },
  {
    question: 'What is a custodial wallet?',
    options: [
      'A wallet where a third party holds the keys',
      'A wallet stored on paper',
      'A wallet with no address',
      'A wallet that only holds NFTs',
    ],
    correctAnswerIndex: 0,
    difficulty: 2,
    topic: 'Wallets',
    explanation: 'In a custodial wallet the provider controls the private keys on the user behalf.',
  },
  {
    question: 'What is an embedded wallet?',
    options: [
      'A wallet created inside an app so the user needs no extension',
      'A wallet burned into hardware at the factory',
      'A wallet that lives inside a smart contract only',
      'A wallet shared between all users',
    ],
    correctAnswerIndex: 0,
    difficulty: 2,
    topic: 'Wallets',
    explanation: 'Embedded wallets are provisioned by the application at sign-in, removing extensions and seed-phrase setup.',
  },
  {
    question: 'What does a block explorer let you do?',
    options: [
      'Inspect transactions, blocks and contracts',
      'Mine new blocks',
      'Generate private keys',
      'Deploy a validator automatically',
    ],
    correctAnswerIndex: 0,
    difficulty: 1,
    topic: 'Web3 Basics',
    explanation: 'An explorer indexes chain data so anyone can look up a transaction hash, address or contract.',
  },
  {
    question: 'What is gas estimation used for?',
    options: [
      'Predicting the gas a transaction will consume before sending it',
      'Choosing which validator signs a block',
      'Compressing calldata',
      'Setting the chain id',
    ],
    correctAnswerIndex: 0,
    difficulty: 2,
    topic: 'Web3 Basics',
    explanation: 'Clients simulate the call to estimate gas so the transaction is funded well enough to succeed.',
  },
  {
    question: 'Which of these should never be stored in frontend code?',
    options: [
      'A treasury private key',
      'A public RPC URL',
      'A contract address',
      'A chain id',
    ],
    correctAnswerIndex: 0,
    difficulty: 2,
    topic: 'Smart Contract Security',
    explanation: 'Anything in the frontend bundle is public. Signing keys belong only in server-side environment variables.',
  },
  {
    question: 'What is a chain reorganisation?',
    options: [
      'Replacing recent blocks with a different branch',
      'Renaming a network',
      'Upgrading a smart contract',
      'Rotating an RPC endpoint',
    ],
    correctAnswerIndex: 0,
    difficulty: 4,
    topic: 'Layer 1s',
    explanation: 'A reorg happens when nodes converge on a competing branch, discarding blocks that were previously at the tip.',
  },
  {
    question: 'What does calldata refer to in the EVM?',
    options: [
      'Read-only input data supplied with a call',
      'A contract storage slot',
      'The stack of the current frame',
      'The gas refund counter',
    ],
    correctAnswerIndex: 0,
    difficulty: 4,
    topic: 'Solidity',
    explanation: 'Calldata is the immutable input region for a message call and is the cheapest place to read arguments from.',
  },
  {
    question: 'Why do many protocols emit events instead of storing data on-chain?',
    options: [
      'Logs are far cheaper than storage and are indexable off-chain',
      'Events are encrypted',
      'Events cannot be read by anyone',
      'Storage is not available to contracts',
    ],
    correctAnswerIndex: 0,
    difficulty: 3,
    topic: 'Solidity',
    explanation: 'Event logs cost much less gas than storage writes and indexers can reconstruct history from them.',
  },
  {
    question: 'What makes a settlement function idempotent?',
    options: [
      'Repeating it produces no additional effect',
      'It runs faster the second time',
      'It reverts on the first call',
      'It can only be called by the owner',
    ],
    correctAnswerIndex: 0,
    difficulty: 4,
    topic: 'Smart Contract Security',
    explanation: 'An idempotent operation records that it already ran, so a retry after a timeout cannot double-pay.',
  },
  {
    question: 'What is the main risk of trusting a client-reported score in a game?',
    options: [
      'The client can forge it',
      'It uses too much bandwidth',
      'It cannot be serialised',
      'It breaks the leaderboard sort',
    ],
    correctAnswerIndex: 0,
    difficulty: 2,
    topic: 'Web3 Basics',
    explanation: 'Anything computed on a device the player controls can be modified, so scoring must stay server-authoritative.',
  },
  {
    question: 'What is a testnet faucet?',
    options: [
      'A service that hands out valueless test tokens',
      'A tool that mints real assets',
      'A type of liquidity pool',
      'A consensus client',
    ],
    correctAnswerIndex: 0,
    difficulty: 1,
    topic: 'Web3 Basics',
    explanation: 'Faucets distribute free testnet tokens so developers can pay test gas without real money.',
  },
  {
    question: 'Which property makes a hash function suitable for blockchains?',
    options: [
      'Deterministic output with collision resistance',
      'Reversibility',
      'Variable-length output',
      'Randomised output per call',
    ],
    correctAnswerIndex: 0,
    difficulty: 3,
    topic: 'Web3 Basics',
    explanation: 'The same input always hashes to the same digest, and finding two inputs with one digest must be infeasible.',
  },
];

export const QUIZ_SEED: Seed[] = SEEDS;

export const QUIZ_TOPICS = Array.from(new Set(SEEDS.map((seed) => seed.topic))).sort();
