import type { Challenge } from '@/lib/types';

type Seed = Omit<Challenge, 'id' | 'gameType' | 'source' | 'status'>;

/**
 * Songless clip catalogue.
 *
 * Clips are generated by `scripts/generate-audio.mjs` from public-domain
 * melodies, so the whole mode is legally safe to bundle and works with no
 * external music API. File names are opaque (`track-07.wav`) so the answer is
 * never guessable from network traffic or devtools.
 *
 * The catalogue lives behind `lib/content/songless-provider.ts`, which is the
 * seam where a licensed external provider can be swapped in later.
 */
export interface SonglessTrack {
  file: string;
  title: string;
  /** Used to build plausible decoys within the same style. */
  era: 'classical' | 'traditional';
  difficulty: number;
  hint: string;
}

export const SONGLESS_TRACKS: SonglessTrack[] = [
  { file: 'track-01.wav', title: 'Ode to Joy', era: 'classical', difficulty: 1, hint: 'Beethoven, from the Ninth Symphony.' },
  { file: 'track-02.wav', title: 'Für Elise', era: 'classical', difficulty: 1, hint: 'One of the most recognisable piano bagatelles ever written.' },
  { file: 'track-03.wav', title: 'Twinkle Twinkle Little Star', era: 'traditional', difficulty: 1, hint: 'A nursery melody Mozart also wrote variations on.' },
  { file: 'track-04.wav', title: 'Greensleeves', era: 'traditional', difficulty: 2, hint: 'An English folk tune dating to the 16th century.' },
  { file: 'track-05.wav', title: 'Canon in D', era: 'classical', difficulty: 3, hint: 'Pachelbel, and the chord progression behind countless pop songs.' },
  { file: 'track-06.wav', title: 'William Tell Overture', era: 'classical', difficulty: 2, hint: 'Rossini, and the definitive galloping finale.' },
  { file: 'track-07.wav', title: 'In the Hall of the Mountain King', era: 'classical', difficulty: 2, hint: 'Grieg, from the Peer Gynt suite — it accelerates relentlessly.' },
  { file: 'track-08.wav', title: 'Eine kleine Nachtmusik', era: 'classical', difficulty: 3, hint: 'Mozart, a serenade whose opening everyone knows.' },
  { file: 'track-09.wav', title: 'The Blue Danube', era: 'classical', difficulty: 3, hint: 'A Strauss waltz in three-four time.' },
  { file: 'track-10.wav', title: 'Jingle Bells', era: 'traditional', difficulty: 1, hint: 'Written in the 1850s, now inseparable from winter.' },
  { file: 'track-11.wav', title: 'Frère Jacques', era: 'traditional', difficulty: 2, hint: 'A French round about a sleeping friar.' },
  { file: 'track-12.wav', title: 'Amazing Grace', era: 'traditional', difficulty: 2, hint: 'An 18th-century hymn, usually sung to the tune "New Britain".' },
];

function shuffleDeterministic<T>(items: T[], seed: number): T[] {
  const output = items.slice();
  let state = (seed * 22695477 + 1) >>> 0;
  for (let i = output.length - 1; i > 0; i -= 1) {
    state = (state * 22695477 + 1) >>> 0;
    const j = state % (i + 1);
    [output[i], output[j]] = [output[j], output[i]];
  }
  return output;
}

/** Build a four-option challenge for one track, drawing decoys from the rest. */
export function trackToChallenge(track: SonglessTrack, index: number): Seed {
  const sameEra = SONGLESS_TRACKS.filter(
    (candidate) => candidate.file !== track.file && candidate.era === track.era,
  );
  const otherEra = SONGLESS_TRACKS.filter(
    (candidate) => candidate.file !== track.file && candidate.era !== track.era,
  );
  const pool = [...shuffleDeterministic(sameEra, index + 3), ...shuffleDeterministic(otherEra, index + 11)];
  const decoys = pool.slice(0, 3).map((candidate) => candidate.title);
  const options = shuffleDeterministic([track.title, ...decoys], index + 5);

  return {
    question: 'Listen to the clip. Which melody is playing?',
    options,
    correctAnswerIndex: options.indexOf(track.title),
    difficulty: track.difficulty,
    topic: track.era === 'classical' ? 'Classical' : 'Traditional',
    explanation: `${track.title} — ${track.hint}`,
    audioUrl: `/audio/${track.file}`,
  };
}

export const SONGLESS_SEED: Seed[] = SONGLESS_TRACKS.map(trackToChallenge);

export const SONGLESS_TOPICS = ['Classical', 'Traditional'];
